### PR TITLE
[TASK] Allow to sort organizations list by backend sorting

### PR DESCRIPTION
**Pull request by Hasan-Shaker**

### CODE REVIEW

**Comment by xperseguers** [comment]
I don't get why you want to manually sort the list of organizations. This makes no sense to me.

We have a default sort by, which is logically the name. If you want to sort by some other way, you can show additional columns in TYPO3 Backend and then use the header to sort on that property.

With that, the user will have to manually sort their organizations. Why???

**Comment by Hasan-Shaker** [comment]
Hello,
this was requested by JBH. we can also keep default_sortby

**Comment by xperseguers** [comment]
That's not valid, sorry :) you have to explain why you need that, and why you think this is the only way to do so. For the reasons I gave, it doesn't look like a legit requirement to do that in that extension. This just feels wrong. If that's something you need for a specific project, maybe there's something to do in that project but change in the extension for everyone needs to be legitimated more than "someone wants that".

**Comment by Hasan-Shaker** [comment]
Ok, we can do it directly in the project, but we think it's logical to have a custom list sort in the extension.

**Pull request closed without merging**
